server:
  port: 80
  http:
    encoding:
      charset: utf8
    #文件上传限制
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  tomcat:
    uri-encoding: UTF-8

spring:
  resources:
    #静态资源目录
    static-locations: classpath:/static/, classpath:/templates/

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hospitalmanage?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #数据库驱动com.mysql.jdbc.Driver'已经被弃用了、应当使用新的驱动com.mysql.cj.jdbc.Driver'
    driver-class-name: com.mysql.cj.jdbc.Driver

    #初始化数据
    schema: classpath:schema.sql
    #data: classpath:data.sql
    sql-script-encoding: utf-8

    #首次启动设置为ALWAYS,之后设置为NEVER
    initialization-mode: ALWAYS

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: graduation.project.hospitalbedsmanage.entity
  config-location: classpath:config/mybatis-config.xml

#日志
logging:
  config: classpath:config/logback.xml
